apiVersion: apps/v1
kind: Deployment
metadata:
    name: nginx-secureshoot
    labels:
        app: nginx-secureshoot
spec:
 replicas: 1
 selector:
    matchLabels:
        app: nginx-secureshoot
 template:
    metadata:
     labels:
        app: nginx-secureshoot
    spec:
        containers:
        - name: nginx
          image: nginx:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 80
          securityContext:
            allowPrivilegeEscalation: false
            runAsNonRoot: true
            readOnlyRootFilesystem: true
        - name: secureshoot
          image: lordoverlord/secureshoot
          imagePullPolicy: Always
          command: ["/bin/bash"]
          args: ["-c", "while true; do ping localhost; sleep 60;done"]
          securityContext:
            allowPrivilegeEscalation: false
            runAsNonRoot: true
            readOnlyRootFilesystem: true