name: Image build Main

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  REGISTRY: ghcr.io

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Convert repository name to lowercase
        id: repo_name
        run: echo "::set-output name=image_name::${GITHUB_REPOSITORY,,}"  # Set the output to lowercase
        shell: bash

      - name: Log in to the Container registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ${{ env.REGISTRY }}/${{ steps.repo_name.outputs.image_name }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          # Use the lowercase repository name from the repo_name output
          tags: ${{ steps.meta.outputs.tags }},${{ env.REGISTRY }}/${{ steps.repo_name.outputs.image_name }}:latest
          labels: ${{ steps.meta.outputs.labels }}

      - name: Run Snyk to check Docker image for vulnerabilities
        uses: snyk/actions/docker@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          image: ghcr.io/${{ steps.repo_name.outputs.image_name }}:main  # Use lowercase repository name
          command: monitor
